name: Update

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update.yml'
    branches:
      - main
  schedule:
    - cron: 0 16 * * *

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Submodule
        run: sh update.sh
        
      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@github.com"
          git add --all
          git commit -m "$(date +'%Y-%m-%dT%H:%M:%S')"
          git push
       